package:
  name: magpy
  version: 1.0.0

requirements:
  run:
    - python>=3.7
    - numpy>=1.16.5
    - scipy>=1.7

about:
  home: https://www.github.com/brownadder/magpy
  license: MIT
  summary: 'Magnus based time-integration for spins and qubits under a magnetic field.'